title: Stephanie's Sanctuary # Novo Título do Site
baseurl: ""
url: "https://steniechini.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
# --- Configuração de Coleções ---
collections:
  reviews:
    output: true # Garante que as reviews virem páginas individuais
    permalink: /reviews/:path/